# Generated by Django 5.2.8 on 2025-11-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslettersubscriber',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='talle',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], help_text='Solo para Remeras / Buzos / Pantalones. Vacío en accesorios.', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('remeras', 'Remeras'), ('buzos', 'Buzos / Camperas'), ('pantalones', 'Pantalones'), ('accesorios', 'Accesorios')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrito',
            unique_together={('carrito', 'producto', 'talle')},
        ),
    ]
