# Generated by Django 5.2.8 on 2025-12-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_pedido_payment_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mp_merchant_order_id',
            field=models.CharField(blank=True, help_text='Merchant order id (opcional)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_payment_id',
            field=models.CharField(blank=True, help_text='ID de pago en Mercado Pago', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='mp_status',
            field=models.CharField(blank=True, help_text='Estado del pago (approved, rejected, etc.)', max_length=50, null=True),
        ),
    ]
