# Generated by Django 5.2.8 on 2025-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_pedido_mp_merchant_order_id_pedido_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-creado']},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='image_hover',
        ),
        migrations.AddField(
            model_name='producto',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('hoodies', 'Buzos / Camperas'), ('pants', 'Pantalones'), ('tees', 'Remeras'), ('accessories', 'Accesorios')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tag',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
