# Generated by Django 5.2.8 on 2025-12-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_producto_imagen_alter_producto_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='actualizado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creado',
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_hover',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=models.SlugField(max_length=120, unique=True),
        ),
    ]
