# Generated by Django 5.2.8 on 2025-12-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_producto_actualizado_remove_producto_creado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle y número'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
    ]
